# Generated by Django 5.2.1 on 2025-05-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_user_id_user_address_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('associate_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
